CREATE TABLE t0 (c0 INTEGER UNIQUE, c1 INTEGER, c2 TEXT UNIQUE, c3 TEXT UNIQUE);
CREATE INDEX i8 ON t0(c1) WHERE NULL;
INSERT INTO t0 (c0, c1, c2, c3) VALUES (1, 1, '', '');
SELECT 1 FROM t0 WHERE (t0.c1) IN (SELECT t0.c1 FROM t0)