CREATE TABLE T1 (c1 REAL, c2 JSON, c3 REAL NOT NULL DEFAULT NULL);
CREATE TABLE T2 (c1 JSON);
CREATE TABLE T3 (c1 REAL, c2 BLOB);
INSERT INTO T1 (c1, c2, c3) VALUES (1, '', -1);
INSERT INTO T3 (c1, c2) VALUES (1, 1);
SELECT DISTINCT 1 FROM T1 AS a LEFT JOIN T2 AS b ON a.c3 = b.c1 LEFT JOIN T3 AS c ON b.c1 = c.c2 WHERE c.c1 > a.c3